networks:
  default:

services:
  solr:
    image: solr:9.8.1
    command:
      - solr-foreground
      - -c
    environment:
      SOLR_OPTS: -Dsolr.jetty.request.header.size=65536 -Dsolr.dns.prevent.reverse.lookup
    ulimits:
      nofile:
        soft: 65000
        hard: 65000
    hostname: solr
    container_name: solr
    volumes:
      - "./ckanext-hdx_search/ckanext/hdx_search/hdx-solr/schema.xml:/opt/solr/server/solr/configsets/_default/conf/managed-schema"

  db:
    image: postgis/postgis:14-3.4-alpine
    hostname: db
    container_name: db
    environment:
      POSTGRES_PASSWORD: ckan
      POSTGRES_USER: ckan
      POSTGRES_DB: ckan
    networks:
      default:
        aliases:
          - dbckan

  ckan:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: ckan
    depends_on:
      - db
      - solr
    volumes:
      - "./.git:/srv/ckan/.git"
    environment:
      HDX_HOURS_MIXPANEL_CACHE: 1
      HDX_CKANDB_ADDR: 'dbckan'
      HDX_CKANDB_PORT: 5432
      HDX_CKANDB_DB: ckan
      HDX_CKANDB_USER: ckan
      HDX_CKANDB_PASS: ckan
      HDX_CKANDB_USER_DATASTORE: datastore
      HDX_CKANDB_DB_DATASTORE: datastore
      HDX_CKANDB_DB_TEST: ckan_test
      HDX_CKANDB_DB_TEST_DATASTORE: datastore
      HDX_CKANDB_PASS_DATASTORE: datastore
      HDX_DOMAIN: humdata.org
      HDX_FILESTORE: /srv/filestore
      HDX_SOLR_ADDR: solr
      HDX_SOLR_PORT: 8983
      HDX_TYPE: ${HDX_TYPE}
      HDX_SMTP_ADDR: localhost
      HDX_SMTP_PORT: 25
      HDX_SMTP_USER: ''
      HDX_SMTP_PASS: ''
      HDX_SMTP_TLS: 'False'
      GITHUB_TOKEN: ${GITHUB_TOKEN:-NO_TOKEN_PROVIDED}
      COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN:-NO_TOKEN_PROVIDED}
      AWS_ACCESS_KEY_ID: RANDOM_KEY
      AWS_SECRET_ACCESS_KEY: RANDOM_SECRET_KEY
      AWS_BUCKET_NAME: RANDOM_BUCKET
      REGION_NAME: eu-central-1
      HDX_ENABLED_PLUGINS: dcat dcat_json_interface structured_data hdx_dataviz expire_api_token hdx_hxl_preview ytp_request hdx_pages hdx_choropleth_map_view hdx_geopreview_view hdx_chart_views hdx_service_checker hdx_analytics hdx_search sitemap hdx_org_group hdx_group hdx_package hdx_user_extra hdx_mail_validate hdx_users hdx_theme security requestdata showcase resource_proxy text_view recline_view datastore
