
questions_list = {
    'data_protection_checklist': {
     'dp1': 'The dataset contains survey data',
     'dp2': 'The dataset is not safe to share or is potentially sensitive',
     'dp3': 'If the dataset is potentially sensitive; I have made the dataset private',
     'dp4': 'If the dataset is potentially sensitive; I have informed the dataset contributor by email (copy Jos, Nafi and hdx@un.org) that the dataset has been taken down.',
     'dp5': 'If the dataset is potentially sensitive; I have made an entry in the SDC for Microdata Log',
     'dp6': 'If the dataset is potentially sensitive, I have informed Nafi and Jos in the Duty Roster Chat on Skpe for disclosure control purposes',
    },
    'metadata_checklist': {
        'm1': 'The dataset has NOT a title',
        'm2': 'The dataset title is NOT consistent with the data actually contained in the datataset',
        'm3': 'The dataset title is NOT in camel case',
        'm4': 'The dataset title DOES NOT start with the name of the (place) country, region or place to which the data refers.',
        'm5': 'The dataset title does NOT include a relative time reference such as current, latest, new, old',
        'm6': 'The dataset has NOT a description',
        'm7': 'The description DOES NOT accurately describe the data in the resources',
        'm8': 'The description is NOT free of personal information like the name of a contact or their email address. Generic email addresses are fine. ',
        'm9': 'The dataset has NOT a source',
        'm10': 'The source is listed as Multiple Sources',
        'm11': 'If the source is listed as Multiple Sources; the multiple sources are clearly listed elsewhere in the dataset (such as in the description, comments or additional metadata file)',
        'm12': 'The source is NOT a valid source or is listed as UNOCHA',
        'm13': 'The dataset has NOT a Date of Dataset',
        'm14': 'The Date of Dataset is a date in the future',
        'm15': 'The date of dataset is NOT consistent with the updateness of the data. In other words, the data is NOT as up-to-date as is suggested by the date of dataset',
        'm16': 'The dataset has NOT an Expected Update Frequency',
        'm17': 'The data is NOT fresh according to the Expected Update Frequency',
        'm18': 'The dataset has NOT at least one location',
        'm19': 'The locations specified in the dataset DO NOT correspond to the locations that the data actually refers to',
        'm20': 'The dataset has NO a license',
        'm21': 'The license is "OTHER"',
        'm22': 'If the license is "OTHER", the text in the LICENSE OTHER field DOES NOT describe clear and meaningful license terms',
        'm23': 'The dataset has NOT a methodology',
        'm24': 'The methodology is "OTHER"',
        'm25': 'If the methodology is "OTHER", the text in the METHODOLOGY OTHER box DOES NOT describe a clear and meaningful methodology.',
        'm26': 'The  Caveat/Comments text is NOT meaningful',
        'm27': 'Does the dataset have subnational data',
        'm28': 'If the dataset contains subnational data, the Dataset DOES NOT have the SUB-NATIONAL flag',
        'm29': 'If the dataset does NOT contain sub-national data,  the dataset has the SUB-NATIONAL flag',
        'm30': 'No embedded dataviz is working',
        'm31': 'The quickcharts showing on the dataviz don\'t make sense',
        'm32': 'The dataset has zipped shapefiles, but the geopreview is not working'
    },
    'resources_checklist':{
        'r1': 'The download link is NOT working',
        'r2': 'The download link requires a password',
        'r3': 'I have NOT downloaded and reviewed the file',
        'r4': 'The data file is in unusuable data format such as PDF or WORD (and not in XLS/X, CSV, SHP)',
        'r5': 'The data file is a PDF (acceptable only if it contains metadata)',
        'r6': 'There is PII in the data file',
        'r7': 'There is DII in the data file',
        'r8': 'There is individual survey data in the data file',
        'r9': 'The file type is NOT consistent with the file\'s actual file type',
        'r10': 'The file contains a zipped shapefile and the file type is NOT correctly set as "zipped shapefile"',
    }
}
