from ckanext.hdx_theme.helpers.ui_constants.onboarding.user_info import CONSTANTS as USER_INFO_CONSTANTS

CONSTANTS = {
    'STEPS_1': USER_INFO_CONSTANTS['STEPS_1'],
    'STEPS_2': USER_INFO_CONSTANTS['STEPS_2'],
    'STEPS_3': USER_INFO_CONSTANTS['STEPS_3'],

    'PAGE_TITLE': '''Re-enter your email address''',

    'INPUT_EMAIL_LABEL': '''Enter your email address''',
    'INPUT_EMAIL_PLACEHOLDER': USER_INFO_CONSTANTS['INPUT_EMAIL_PLACEHOLDER'],
    'INPUT_EMAIL_ERROR': USER_INFO_CONSTANTS['INPUT_EMAIL_ERROR'],
    'INPUT_EMAIL2_LABEL': USER_INFO_CONSTANTS['INPUT_EMAIL2_LABEL'],
    'INPUT_EMAIL2_PLACEHOLDER': USER_INFO_CONSTANTS['INPUT_EMAIL2_PLACEHOLDER'],
    'INPUT_EMAIL2_ERROR': USER_INFO_CONSTANTS['INPUT_EMAIL2_ERROR'],

    'BUTTON_SUBMIT': '''Next''',
}
