CONSTANTS = {
    'STEPS_1': '''Details''',
    'STEPS_2': '''Submitted''',

    'PAGE_TITLE': '''Request to create a new organisation''',
    'MANDATORY_HELP': '''* indicates mandatory fields''',

    'BODY_INFO_1ST_PARAGRAPH': '''Please tell us about the organisation that you want to create on HDX. An organisation on HDX can be a legal entity or an informal group.''',
    'BODY_INFO_2ND_PARAGRAPH': '''The HDX team will use the information you provide to accept or decline your request and they may contact you for further information.''',

    'INPUT_NAME_LABEL': '''What is the name of the organisation?''',
    'INPUT_NAME_PLACEHOLDER': '''Name of organisation''',
    'INPUT_NAME_ERROR': '''Name cannot be empty''',
    'TEXTAREA_DESCRIPTION_LABEL': '''Provide a description of the organisation including its focus, location and activities''',
    'TEXTAREA_DESCRIPTION_PLACEHOLDER': '''''',
    'TEXTAREA_DESCRIPTION_ERROR': '''Description cannot be empty''',
    'INPUT_WEBSITE_LABEL': '''Please share the website of the organisation''',
    'INPUT_WEBSITE_PLACEHOLDER': '''https://''',
    'INPUT_WEBSITE_ERROR': '''''',
    'INPUT_ROLE_LABEL': '''Explain your role within the organisation''',
    'INPUT_ROLE_PLACEHOLDER': '''''',
    'INPUT_ROLE_ERROR': '''Role cannot be empty''',
    'TEXTAREA_DATA_TYPE_LABEL': '''What type of data would your organisation like to share? Please include details about the topics and locations covered by the data, along with the format''',
    'TEXTAREA_DATA_TYPE_PLACEHOLDER': '''Education statistics, possibly school locations, and other secondary data for Somalia in CSV format''',
    'TEXTAREA_DATA_TYPE_ERROR': '''Type of data cannot be empty''',
    'SELECT_DATA_ALREADY_AVAILABLE_LABEL': '''Is the data already available publicly through a website?''',
    'SELECT_DATA_ALREADY_AVAILABLE_PLACEHOLDER': '''Select an option...''',
    'SELECT_DATA_ALREADY_AVAILABLE_ERROR': '''Data already available cannot be empty''',
    'INPUT_DATA_ALREADY_AVAILABLE_LINK_LABEL': '''If yes, please provide a link''',
    'INPUT_DATA_ALREADY_AVAILABLE_LINK_PLACEHOLDER': '''https://''',
    'INPUT_DATA_ALREADY_AVAILABLE_LINK_ERROR': '''''',

    'BUTTON_SUBMIT': '''Submit''',
    'BUTTON_CANCEL': '''Cancel''',
}
