var countries = {
    "A": [
        ["AFG", "Afghanistan"],
        ["ALA", "\u00c5land Islands"],
        ["ALB", "Albania"],
        ["DZA", "Algeria"],
        ["ASM", "American Samoa"],
        ["AND", "Andorra"],
        ["AGO", "Angola"],
        ["AIA", "Anguilla"],
        ["ATA", "Antarctica"],
        ["ATG", "Antigua and Barbuda"],
        ["ARG", "Argentina"],
        ["ARM", "Armenia"],
        ["ABW", "Aruba"],
        ["AUS", "Australia"],
        ["AUT", "Austria"],
        ["AZE", "Azerbaijan"]
    ],
    "B": [
        ["BHS", "Bahamas"],
        ["BHR", "Bahrain"],
        ["BGD", "Bangladesh"],
        ["BRB", "Barbados"],
        ["BLR", "Belarus"],
        ["BEL", "Belgium"],
        ["BLZ", "Belize"],
        ["BEN", "Benin"],
        ["BMU", "Bermuda"],
        ["BTN", "Bhutan"],
        ["BOL", "Bolivia (Plurinational State of)"],
        ["BES", "Bonaire, Sint Eustatius and Saba"],
        ["BIH", "Bosnia and Herzegovina"],
        ["BWA", "Botswana"],
        ["BVT", "Bouvet Island"],
        ["BRA", "Brazil"],
        ["IOT", "British Indian Ocean Territory"],
        ["VGB", "British Virgin Islands"],
        ["BRN", "Brunei Darussalam"],
        ["BGR", "Bulgaria"],
        ["BFA", "Burkina Faso"],
        ["BDI", "Burundi"]
    ],
    "C": [
        ["KHM", "Cambodia"],
        ["CMR", "Cameroon"],
        ["CAN", "Canada"],
        ["CPV", "Cape Verde"],
        ["CYM", "Cayman Islands"],
        ["CAF", "Central African Republic"],
        ["TCD", "Chad"],
        ["CHL", "Chile"],
        ["CHN", "China"],
        ["HKG", "China, Hong Kong Special Administrative Region"],
        ["MAC", "China, Macao Special Administrative Region"],
        ["CXR", "Christmas Island"],
        ["CCK", "Cocos (Keeling) Islands"],
        ["COL", "Colombia"],
        ["COM", "Comoros"],
        ["COG", "Congo"],
        ["COK", "Cook Islands"],
        ["CRI", "Costa Rica"],
        ["CIV", "C\u00f4te d'Ivoire"],
        ["HRV", "Croatia"],
        ["CUB", "Cuba"],
        ["CUW", "Cura\u00e7ao"],
        ["CYP", "Cyprus"],
        ["CZE", "Czech Republic"]
    ],
    "D": [
        ["PRK", "Democratic People's Republic of Korea"],
	["COD", "Democratic Republic of the Congo"],
        ["DNK", "Denmark"],
        ["DJI", "Djibouti"],
        ["DMA", "Dominica"],
        ["DOM", "Dominican Republic"]
    ],
    "E": [
        ["ECU", "Ecuador"],
        ["EGY", "Egypt"],
        ["SLV", "El Salvador"],
        ["GNQ", "Equatorial Guinea"],
        ["ERI", "Eritrea"],
        ["EST", "Estonia"],
        ["SWZ", "Eswatini"],
        ["ETH", "Ethiopia"]
    ],
    "F": [
        ["FLK", "Falkland Islands (Malvinas)"],
        ["FRO", "Faroe Islands"],
        ["FJI", "Fiji"],
        ["FIN", "Finland"],
        ["FRA", "France"],
        ["GUF", "French Guiana"],
        ["PYF", "French Polynesia"],
        ["ATF", "French Southern Territories"]
    ],
    "G": [
        ["GAB", "Gabon"],
        ["GMB", "Gambia"],
        ["GEO", "Georgia"],
        ["DEU", "Germany"],
        ["GHA", "Ghana"],
        ["GIB", "Gibraltar"],
        ["GRC", "Greece"],
        ["GRL", "Greenland"],
        ["GRD", "Grenada"],
        ["GLP", "Guadeloupe"],
        ["GUM", "Guam"],
        ["GTM", "Guatemala"],
        ["GGY", "Guernsey"],
        ["GIN", "Guinea"],
        ["GNB", "Guinea-Bissau"],
        ["GUY", "Guyana"]
    ],
    "H": [
        ["HTI", "Haiti"],
        ["HMD", "Heard Island and McDonald Islands"],
        ["VAT", "Holy See (Vatican City State)"],
        ["HND", "Honduras"],
        ["HUN", "Hungary"]
    ],
    "I": [
        ["ISL", "Iceland"],
        ["IND", "India"],
        ["IDN", "Indonesia"],
        ["IRN", "Iran (Islamic Republic of)"],
        ["IRQ", "Iraq"],
        ["IRL", "Ireland"],
        ["IMN", "Isle of Man"],
        ["ISR", "Israel"],
        ["ITA", "Italy"]
    ],
    "J": [
        ["JAM", "Jamaica"],
        ["JPN", "Japan"],
        ["JEY", "Jersey"],
        ["JOR", "Jordan"]
    ],
    "K": [
        ["KAZ", "Kazakhstan"],
        ["KEN", "Kenya"],
        ["KIR", "Kiribati"],
        ["KWT", "Kuwait"],
        ["KGZ", "Kyrgyzstan"]
    ],
    "L": [
        ["LAO", "Lao People's Democratic Republic"],
        ["LVA", "Latvia"],
        ["LBN", "Lebanon"],
        ["LSO", "Lesotho"],
        ["LBR", "Liberia"],
        ["LBY", "Libya"],
        ["LIE", "Liechtenstein"],
        ["LTU", "Lithuania"],
        ["LUX", "Luxembourg"]
    ],
    "M": [
        ["MKD", "North Macedonia"],
        ["MDG", "Madagascar"],
        ["MWI", "Malawi"],
        ["MYS", "Malaysia"],
        ["MDV", "Maldives"],
        ["MLI", "Mali"],
        ["MLT", "Malta"],
        ["MHL", "Marshall Islands"],
        ["MTQ", "Martinique"],
        ["MRT", "Mauritania"],
        ["MUS", "Mauritius"],
        ["MYT", "Mayotte"],
        ["MEX", "Mexico"],
        ["FSM", "Micronesia (Federated States of)"],
        ["MCO", "Monaco"],
        ["MNG", "Mongolia"],
        ["MNE", "Montenegro"],
        ["MSR", "Montserrat"],
        ["MAR", "Morocco"],
        ["MOZ", "Mozambique"],
        ["MMR", "Myanmar"]
    ],
    "N": [
        ["NAM", "Namibia"],
        ["NRU", "Nauru"],
        ["NPL", "Nepal"],
        ["NLD", "Netherlands"],
        ["NCL", "New Caledonia"],
        ["NZL", "New Zealand"],
        ["NIC", "Nicaragua"],
        ["NER", "Niger"],
        ["NGA", "Nigeria"],
        ["NIU", "Niue"],
        ["NFK", "Norfolk Island"],
        ["MNP", "Northern Mariana Islands"],
        ["NOR", "Norway"]
    ],
    "O": [
        ["OMN", "Oman"]
    ],
    "P": [
        ["PAK", "Pakistan"],
        ["PLW", "Palau"],
        ["PAN", "Panama"],
        ["PNG", "Papua New Guinea"],
        ["PRY", "Paraguay"],
        ["PER", "Peru"],
        ["PHL", "Philippines"],
        ["PCN", "Pitcairn"],
        ["POL", "Poland"],
        ["PRT", "Portugal"],
        ["PRI", "Puerto Rico"]
    ],
    "Q": [
        ["QAT", "Qatar"]
    ],
    "R": [
        ["KOR", "Republic of Korea"],
        ["MDA", "Republic of Moldova"],
        ["REU", "R\u00e9union"],
        ["ROU", "Romania"],
        ["RUS", "Russian Federation"],
        ["RWA", "Rwanda"]
    ],
    "S": [
        ["BLM", "Saint Barth\u00e9lemy"],
        ["SHN", "Saint Helena, Ascension and Tristan da Cunha"],
        ["KNA", "Saint Kitts and Nevis"],
        ["LCA", "Saint Lucia"],
        ["MAF", "Saint Martin (French part)"],
        ["SPM", "Saint Pierre and Miquelon"],
        ["VCT", "Saint Vincent and the Grenadines"],
        ["WSM", "Samoa"],
        ["SMR", "San Marino"],
        ["STP", "Sao Tome and Principe"],
        ["SAU", "Saudi Arabia"],
        ["SEN", "Senegal"],
        ["SRB", "Serbia"],
        ["SYC", "Seychelles"],
        ["SLE", "Sierra Leone"],
        ["SGP", "Singapore"],
        ["SXM", "Sint Maarten (Dutch part)"],
        ["SVK", "Slovakia"],
        ["SVN", "Slovenia"],
        ["SLB", "Solomon Islands"],
        ["SOM", "Somalia"],
        ["ZAF", "South Africa"],
        ["SGS", "South Georgia and the South Sandwich Islands"],
        ["SSD", "South Sudan"],
        ["ESP", "Spain"],
        ["LKA", "Sri Lanka"],
        ["PSE", "State of Palestine"],
        ["SDN", "Sudan"],
        ["SUR", "Suriname"],
        ["SJM", "Svalbard and Jan Mayen"],
        ["SWE", "Sweden"],
        ["CHE", "Switzerland"],
        ["SYR", "Syrian Arab Republic"]
    ],
    "T": [
        ["TWN", "Taiwan, Province of China"],
        ["TJK", "Tajikistan"],
        ["THA", "Thailand"],
        ["TLS", "Timor-Leste"],
        ["TGO", "Togo"],
        ["TKL", "Tokelau"],
        ["TON", "Tonga"],
        ["TTO", "Trinidad and Tobago"],
        ["TUN", "Tunisia"],
        ["TUR", "Türkiye"],
        ["TKM", "Turkmenistan"],
        ["TCA", "Turks and Caicos Islands"],
        ["TUV", "Tuvalu"]
    ],
    "U": [
        ["UGA", "Uganda"],
        ["UKR", "Ukraine"],
        ["ARE", "United Arab Emirates"],
        ["GBR", "United Kingdom"],
        ["TZA", "United Republic of Tanzania"],
        ["USA", "United States"],
        ["UMI", "United States Minor Outlying Islands"],
        ["VIR", "United States Virgin Islands"],
        ["URY", "Uruguay"],
        ["UZB", "Uzbekistan"]
    ],
    "V": [
        ["VUT", "Vanuatu"],
        ["VEN", "Venezuela (Bolivarian Republic of)"],
        ["VNM", "Viet Nam"],
    ],
    "W": [
        ["WLF", "Wallis and Futuna"],
        ["ESH", "Western Sahara"]
    ],
    "X": [],
    "Y": [
        ["YEM", "Yemen"]
    ],
    "Z": [
        ["ZMB", "Zambia"],
        ["ZWE", "Zimbabwe"]
    ]
};
