var countries = {
    "A": [
        ["AFG", "Afghanistan", 5, 106],
        ["ALA", "\u00c5land Islands"],
        ["ALB", "Albania", 5, 108],
        ["DZA", "Algeria", 4, 107],
        ["ASM", "American Samoa", 5, 41],
        ["AND", "Andorra", 4, 45],
        ["AGO", "Angola", 5, 104],
        ["AIA", "Anguilla", 4, 36],
        ["ATA", "Antarctica", 4, 0],
        ["ATG", "Antigua and Barbuda", 5, 76],
        ["ARG", "Argentina", 5, 103],
        ["ARM", "Armenia", 5, 110],
        ["ABW", "Aruba", 4, 46],
        ["AUS", "Australia", 4, 85],
        ["AUT", "Austria", 4, 80],
        ["AZE", "Azerbaijan", 5, 115]
    ],
    "C": [
        ["KHM", "Cambodia", 5, 115],
        ["CMR", "Cameroon", 6, 125],
        ["CAN", "Canada", 5, 91],
        ["CPV", "Cape Verde", 4, 92],
        ["CYM", "Cayman Islands", 4, 42],
        ["CAF", "Central African Republic", 5, 124],
        ["TCD", "Chad", 6, 126],
        ["CHL", "Chile", 5, 101],
        ["CHN", "China", 5, 100],
        ["CXR", "Christmas Island", 4, 0],
        ["CCK", "Cocos (Keeling) Islands", 4, 0],
        ["COL", "Colombia", 22, 123],
        ["COM", "Comoros", 5, 109],
        ["COG", "Congo", 5, 120],
        ["COD", "Congo, the Democratic Republic of the", 6, 117],
        ["COK", "Cook Islands", 4, 38],
        ["CRI", "Costa Rica", 5, 108],
        ["CIV", "C\u00f4te d'Ivoire", 5, 134],
        ["HRV", "Croatia", 5, 85],
        ["CUB", "Cuba", 5, 84],
        ["CUW", "Cura\u00e7ao"],
        ["CYP", "Cyprus", 4, 77],
        ["CZE", "Czech Republic", 4, 91]
    ],
    "B": [
        ["BHS", "Bahamas", 5, 82],
        ["BHR", "Bahrain", 4, 83],
        ["BGD", "Bangladesh", 5, 117],
        ["BRB", "Barbados", 5, 88],
        ["BLR", "Belarus", 4, 101],
        ["BEL", "Belgium", 4, 81],
        ["BLZ", "Belize", 5, 102],
        ["BEN", "Benin", 6, 120],
        ["BMU", "Bermuda", 4, 42],
        ["BTN", "Bhutan", 5, 101],
        ["BOL", "Bolivia, Plurinational State of", 5, 114],
        ["BES", "Bonaire, Sint Eustatius and Saba"],
        ["BIH", "Bosnia and Herzegovina", 5, 93],
        ["BWA", "Botswana", 5, 104],
        ["BVT", "Bouvet Island", 3, 0],
        ["BRA", "Brazil", 5, 113],
        ["IOT", "British Indian Ocean Territory", 4, 0],
        ["BRN", "Brunei Darussalam", 4, 75],
        ["BGR", "Bulgaria", 5, 91],
        ["BFA", "Burkina Faso", 5, 125],
        ["BDI", "Burundi", 6, 122]
    ],
    "E": [
        ["ECU", "Ecuador", 5, 101],
        ["EGY", "Egypt", 5, 112],
        ["SLV", "El Salvador", 5, 103],
        ["GNQ", "Equatorial Guinea", 5, 96],
        ["ERI", "Eritrea", 4, 111],
        ["EST", "Estonia", 4, 83],
        ["ETH", "Ethiopia", 6, 128]
    ],
    "D": [
        ["DNK", "Denmark", 4, 80],
        ["DJI", "Djibouti", 5, 110],
        ["DMA", "Dominica", 5, 67],
        ["DOM", "Dominican Republic", 5, 112]
    ],
    "G": [
        ["GAB", "Gabon", 5, 114],
        ["GMB", "Gambia", 5, 111],
        ["GEO", "Georgia", 5, 105],
        ["DEU", "Germany", 4, 90],
        ["GHA", "Ghana", 6, 123],
        ["GIB", "Gibraltar", 4, 29],
        ["GRC", "Greece", 4, 82],
        ["GRL", "Greenland", 4, 36],
        ["GRD", "Grenada", 5, 77],
        ["GLP", "Guadeloupe", 4, 40],
        ["GUM", "Guam", 4, 50],
        ["GTM", "Guatemala", 5, 115],
        ["GGY", "Guernsey"],
        ["GIN", "Guinea", 6, 119],
        ["GNB", "Guinea-Bissau", 5, 107],
        ["GUY", "Guyana", 5, 113]
    ],
    "F": [
        ["FLK", "Falkland Islands (Malvinas)", 4, 26],
        ["FRO", "Faroe Islands", 4, 30],
        ["FJI", "Fiji", 5, 93],
        ["FIN", "Finland", 4, 81],
        ["FRA", "France", 4, 81],
        ["GUF", "French Guiana", 4, 40],
        ["PYF", "French Polynesia", 4, 55],
        ["ATF", "French Southern Territories", 4, 0]
    ],
    "I": [
        ["ISL", "Iceland", 4, 76],
        ["IND", "India", 5, 114],
        ["IDN", "Indonesia", 5, 123],
        ["IRN", "Iran, Islamic Republic of", 4, 96],
        ["IRQ", "Iraq", 5, 110],
        ["IRL", "Ireland", 4, 79],
        ["IMN", "Isle of Man"],
        ["ISR", "Israel", 4, 83],
        ["ITA", "Italy", 4, 84]
    ],
    "H": [
        ["HTI", "Haiti", 6, 120],
        ["HMD", "Heard Island and McDonald Islands", 3, 0],
        ["VAT", "Holy See (Vatican City State)", 4, 23],
        ["HND", "Honduras", 5, 116],
        ["HKG", "Hong Kong", 4, 65],
        ["HUN", "Hungary", 4, 94]
    ],
    "K": [
        ["KAZ", "Kazakhstan", 5, 113],
        ["KEN", "Kenya", 28, 128],
        ["KIR", "Kiribati", 4, 78],
        ["PRK", "Korea, Democratic People's Republic of", 5, 84],
        ["KOR", "Korea, Republic of", 5, 85],
        ["KWT", "Kuwait", 4, 93],
        ["KGZ", "Kyrgyzstan", 5, 114]
    ],
    "J": [
        ["JAM", "Jamaica", 5, 102],
        ["JPN", "Japan", 5, 84],
        ["JEY", "Jersey"],
        ["JOR", "Jordan", 5, 110]
    ],
    "M": [
        ["MAC", "Macao", 4, 57],
        ["MKD", "Macedonia, the former Yugoslav Republic of", 5, 93],
        ["MDG", "Madagascar", 6, 119],
        ["MWI", "Malawi", 5, 122],
        ["MYS", "Malaysia", 5, 95],
        ["MDV", "Maldives", 5, 105],
        ["MLI", "Mali", 5, 128],
        ["MLT", "Malta", 4, 78],
        ["MHL", "Marshall Islands", 4, 56],
        ["MTQ", "Martinique", 4, 40],
        ["MRT", "Mauritania", 5, 112],
        ["MUS", "Mauritius", 5, 91],
        ["MYT", "Mayotte", 4, 47],
        ["MEX", "Mexico", 5, 101],
        ["FSM", "Micronesia, Federated States of", 4, 75],
        ["MDA", "Moldova, Republic of", 5, 106],
        ["MCO", "Monaco", 4, 39],
        ["MNG", "Mongolia", 5, 105],
        ["MNE", "Montenegro", 4, 92],
        ["MSR", "Montserrat", 4, 35],
        ["MAR", "Morocco", 5, 113],
        ["MOZ", "Mozambique", 6, 125],
        ["MMR", "Myanmar", 5, 99]
    ],
    "L": [
        ["LAO", "Lao People's Democratic Republic", 6, 108],
        ["LVA", "Latvia", 4, 81],
        ["LBN", "Lebanon", 5, 97],
        ["LSO", "Lesotho", 5, 112],
        ["LBR", "Liberia", 5, 116],
        ["LBY", "Libya", 5, 95],
        ["LIE", "Liechtenstein", 4, 40],
        ["LTU", "Lithuania", 5, 80],
        ["LUX", "Luxembourg", 4, 77]
    ],
    "O": [
        ["OMN", "Oman", 4, 91]
    ],
    "N": [
        ["NAM", "Namibia", 5, 119],
        ["NRU", "Nauru", 4, 41],
        ["NPL", "Nepal", 5, 116],
        ["NLD", "Netherlands", 4, 91],
        ["NCL", "New Caledonia", 4, 56],
        ["NZL", "New Zealand", 4, 80],
        ["NIC", "Nicaragua", 5, 114],
        ["NER", "Niger", 5, 126],
        ["NGA", "Nigeria", 5, 121],
        ["NIU", "Niue", 4, 39],
        ["NFK", "Norfolk Island", 4, 20],
        ["MNP", "Northern Mariana Islands", 5, 41],
        ["NOR", "Norway", 4, 81]
    ],
    "Q": [
        ["QAT", "Qatar", 5, 85]
    ],
    "P": [
        ["PAK", "Pakistan", 5, 122],
        ["PLW", "Palau", 4, 57],
        ["PSE", "Palestine, State of", 5, 74],
        ["PAN", "Panama", 5, 103],
        ["PNG", "Papua New Guinea", 5, 91],
        ["PRY", "Paraguay", 5, 104],
        ["PER", "Peru", 5, 112],
        ["PHL", "Philippines", 5, 123],
        ["PCN", "Pitcairn", 4, 19],
        ["POL", "Poland", 4, 84],
        ["PRT", "Portugal", 4, 83],
        ["PRI", "Puerto Rico", 5, 55]
    ],
    "S": [
        ["BLM", "Saint Barth\u00e9lemy"],
        ["SHN", "Saint Helena, Ascension and Tristan da Cunha", 4, 31],
        ["KNA", "Saint Kitts and Nevis", 5, 66],
        ["LCA", "Saint Lucia", 5, 81],
        ["MAF", "Saint Martin (French part)"],
        ["SPM", "Saint Pierre and Miquelon", 4, 24],
        ["VCT", "Saint Vincent and the Grenadines", 5, 77],
        ["WSM", "Samoa", 4, 83],
        ["SMR", "San Marino", 4, 39],
        ["STP", "Sao Tome and Principe", 6, 111],
        ["SAU", "Saudi Arabia", 4, 96],
        ["SEN", "Senegal", 5, 120],
        ["SRB", "Serbia", 5, 96],
        ["SYC", "Seychelles", 4, 86],
        ["SLE", "Sierra Leone", 6, 119],
        ["SGP", "Singapore", 4, 91],
        ["SXM", "Sint Maarten (Dutch part)"],
        ["SVK", "Slovakia", 4, 78],
        ["SVN", "Slovenia", 4, 84],
        ["SLB", "Solomon Islands", 5, 91],
        ["SOM", "Somalia", 5, 101],
        ["ZAF", "South Africa", 5, 116],
        ["SGS", "South Georgia and the South Sandwich Islands", 4, 0],
        ["SSD", "South Sudan", 7, 77],
        ["ESP", "Spain", 4, 83],
        ["LKA", "Sri Lanka", 5, 110],
        ["SDN", "Sudan", 5, 116],
        ["SUR", "Suriname", 5, 99],
        ["SJM", "Svalbard and Jan Mayen", 3, 19],
        ["SWZ", "Swaziland", 5, 120],
        ["SWE", "Sweden", 4, 81],
        ["CHE", "Switzerland", 4, 81],
        ["SYR", "Syrian Arab Republic", 6, 113]
    ],
    "R": [
        ["REU", "R\u00e9union", 4, 40],
        ["ROU", "Romania"],
        ["RUS", "Russian Federation", 5, 85],
        ["RWA", "Rwanda", 6, 117]
    ],
    "U": [
        ["UGA", "Uganda", 5, 120],
        ["UKR", "Ukraine", 5, 111],
        ["ARE", "United Arab Emirates", 4, 81],
        ["GBR", "United Kingdom", 5, 84],
        ["USA", "United States", 5, 90],
        ["UMI", "United States Minor Outlying Islands", 4, 0],
        ["URY", "Uruguay", 5, 96],
        ["UZB", "Uzbekistan", 5, 110]
    ],
    "T": [
        ["TWN", "Taiwan, Province of China", 4, 0],
        ["TJK", "Tajikistan", 5, 121],
        ["TZA", "Tanzania, United Republic of", 6, 119],
        ["THA", "Thailand", 5, 107],
        ["TLS", "Timor-Leste"],
        ["TGO", "Togo", 5, 118],
        ["TKL", "Tokelau", 4, 34],
        ["TON", "Tonga", 4, 80],
        ["TTO", "Trinidad and Tobago", 5, 94],
        ["TUN", "Tunisia", 5, 102],
        ["TUR", "Turkey", 5, 112],
        ["TKM", "Turkmenistan", 5, 84],
        ["TCA", "Turks and Caicos Islands", 4, 40],
        ["TUV", "Tuvalu", 4, 54]
    ],
    "W": [
        ["WLF", "Wallis and Futuna", 4, 30],
        ["ESH", "Western Sahara", 4, 30]
    ],
    "V": [
        ["VUT", "Vanuatu", 4, 95],
        ["VEN", "Venezuela, Bolivarian Republic of", 5, 96],
        ["VNM", "Viet Nam", 5, 114],
        ["VGB", "Virgin Islands, British", 4, 36],
        ["VIR", "Virgin Islands, U.S.", 4, 50]
    ],
    "Y": [
        ["YEM", "Yemen", 21, 116]
    ],
    "X": [],
    "Z": [
        ["ZMB", "Zambia", 5, 118],
        ["ZWE", "Zimbabwe", 5, 123]
    ]
};
