#!/usr/bin/with-contenv sh

# preparing to run ckan...
bash /srv/ckan/docker/ckan_helper.sh

cd /srv/ckan

[ -z "$NEW_RELIC_APP_NAME"     ] && export NEW_RELIC_APP_NAME="Python Application"
[ -z "$NEW_RELIC_CONFIG_FILE"  ] && export NEW_RELIC_CONFIG_FILE=/srv/newrelic.ini
[ -z "$NEW_RELIC_ENABLED"      ] && export NEW_RELIC_ENABLED=false
[ -z "$NEW_RELIC_LICENSE_KEY"  ] && export NEW_RELIC_LICENSE_KEY="LICENSE"
[ -z "$NEW_RELIC_LOG"          ] && export NEW_RELIC_LOG=false
[ -z "$HDX_QA_DASHBOARD"       ] && export HDX_QA_DASHBOARD=false

[ -z "HDX_ANALYTICS_TRACK_API" ]                    && export HDX_ANALYTICS_TRACK_API=false
[ -z "HDX_ANALYTICS_TRACK_API_EXCLUDE_BROWSERS" ]   && export HDX_ANALYTICS_TRACK_API_EXCLUDE_BROWSERS=
[ -z "HDX_ANALYTICS_TRACK_API_EXCLUDE_OTHER" ]      && export HDX_ANALYTICS_TRACK_API_EXCLUDE_OTHER=

if [ "$NEW_RELIC_ENABLED" = true ]; then
    echo "new relic is enabled."
    newrelic-admin generate-config $NEW_RELIC_LICENSE_KEY $NEW_RELIC_CONFIG_FILE
    exec newrelic-admin run-program gunicorn -w ${HDX_CKAN_WORKERS} --paste /etc/ckan/prod.ini -c /srv/ckan/docker/gunicorn_conf.py
else
    echo "new relic is disabled."
    exec gunicorn -w ${HDX_CKAN_WORKERS} --paste /etc/ckan/prod.ini -c /srv/ckan/docker/gunicorn_conf.py
fi
