#!/usr/bin/with-contenv sh

[ -z "$HDX_SOLR_ADDR" ] && export HDX_SOLR_ADDR="solr"
[ -z "$HDX_SOLR_PORT" ] && export HDX_SOLR_PORT="8983"
[ -z "$HDX_SOLR_CORE" ] && export HDX_SOLR_CORE="ckan"

# normalize log bucket env var (remove this after 2021.05.30)
[ -z "$HDX_ECHO_LOG_BUCKET_NAME" ] && export HDX_ECHO_LOG_BUCKET_NAME=${AWS_BUCKET_NAME}-log

[ -z "$NEW_RELIC_ENABLED"      ] && export NEW_RELIC_ENABLED="false"
[ -z "$ELASTIC_APM_ENABLED"    ] && export ELASTIC_APM_ENABLED="false"

[ -z "$HDX_ANALYTICS_TRACK_API" ]                  && export HDX_ANALYTICS_TRACK_API=false
[ -z "$HDX_ANALYTICS_TRACK_API_EXCLUDE_BROWSERS" ] && export HDX_ANALYTICS_TRACK_API_EXCLUDE_BROWSERS=
[ -z "$HDX_ANALYTICS_TRACK_API_EXCLUDE_OTHER" ]    && export HDX_ANALYTICS_TRACK_API_EXCLUDE_OTHER=

[ -z "$BEAKER_SECRET" ] && export BEAKER_SECRET="ankhs7PHSoJLZ42Lr2901rlfa"

[ -z "$HDX_ENABLED_DATASETS_CSV" ] && export HDX_ENABLED_DATASETS_CSV="https://docs.google.com/spreadsheets/d/e/2PACX-1vSsBSUTM3f9olyhVFDcAh-tXV63wlOtvsXukQIHTLiLCfbGJC8osDDaEqzoUVs2B0kgYMrkyVkihvVm/pub?gid=0&single=true&output=csv"

# provide mailchimp defaults (mailchimp is enabled in common config)
export HDX_MAILCHIMP_API_KEY=${HDX_MAILCHIMP_API_KEY:-ccc-fake}
export HDX_MAILCHIMP_INTEREST_DATA_SERVICES=${HDX_MAILCHIMP_INTEREST_DATA_SERVICES:-90c34fef41}
export HDX_MAILCHIMP_LIST_NEW_USER=${HDX_MAILCHIMP_LIST_NEW_USER:-564eb8df33}
export HDX_MAILCHIMP_LIST_NEWSLETTER=${HDX_MAILCHIMP_LIST_NEWSLETTER:-d937b36390}

# preparing to run ckan...
bash /srv/ckan/docker/ckan_helper.sh

cd /srv/ckan

ln -sf /etc/ckan/prod.ini ckan.ini

if [ "$NEW_RELIC_ENABLED" = "true" ]; then
    [ -z "$NEW_RELIC_APP_NAME"     ] && export NEW_RELIC_APP_NAME="HDX"
    [ -z "$NEW_RELIC_LICENSE_KEY"  ] && export NEW_RELIC_LICENSE_KEY="LICENSE"
    [ -z "$NEW_RELIC_LOG"          ] && export NEW_RELIC_LOG="false"
    echo "new relic is enabled."
    cp /srv/ckan/docker/unit-nr.json /var/lib/unit/conf.json
    chmod 600 /var/lib/unit/conf.json
elif [ "$ELASTIC_APM_ENABLED" = "true" ]; then
    [ -z "$ELASTIC_APM_SERVICE_NAME" ] && export ELASTIC_APM_SERVICE_NAME=HDX
    [ -z "$ELASTIC_APM_ENVIRONMENT" ] && export ELASTIC_APM_ENVIRONMENT=blah
    [ -z "$ELASTIC_APM_SECRET_TOKEN" ] && export ELASTIC_APM_SECRET_TOKEN=
    [ -z "$ELASTIC_APM_SERVER_URL" ] && export ELASTIC_APM_SERVER_URL=
    echo "elk apm is enabled."
    cp /srv/ckan/docker/unit-elk.json /var/lib/unit/conf.json
    chmod 600 /var/lib/unit/conf.json
else
    echo "new relic is disabled."
    cp /srv/ckan/docker/unit.json /var/lib/unit/conf.json
    chmod 600 /var/lib/unit/conf.json
fi

# build all webassets
hdxckantool webassets

# do this when all is peachy: curl -X PUT --data-binary '{"application":"ckan"}' 'localhost:8080/config/listeners/*:5000'
exec unitd --no-daemon --control 127.0.0.1:8080 --user www-data --group www-data --log /var/log/ckan/error.log
