#!/bin/bash

# just for travis, until this PR is merged into dev
mkdir -p /etc/ckan
[ -f /etc/ckan/prod.ini.tpl ] && cp -a /srv/ckan/docker/prod.ini.tpl /etc/ckan

# configure prod.ini
[ -f /etc/ckan/prod.ini.tpl ] && envsubst < /etc/ckan/prod.ini.tpl > /etc/ckan/prod.ini
# and a copy of it to be used by less compile verbose mode
[ -f /etc/ckan/prod.ini.tpl ] && cat /etc/ckan/prod.ini | sed 's/level = WARNING/level = INFO/' > /etc/ckan/less.ini;
#configure test ini
[ -f /srv/ckan/hdx-test-core.ini ] && envsubst < /srv/ckan/docker/hdx-test-core.ini.tpl > /srv/ckan/hdx-test-core.ini

# fix permissions on filestore
mkdir -p /srv/filestore /srv/backup /var/log/ckan
#chown www-data:www-data -R /srv/filestore/
#chown www-data:www-data -R /var/log/ckan
#chown root:root -R /srv/backup

python /srv/ckan/docker/helper.py

# set pgpass if it's not there
hdxckantool pgpass > /dev/null
# set proper permissions on datastore
hdxckantool db set-perms > /dev/null

# make ckan dependent on pgb
#sv start pgb || exit 1

#hdxckantool less compile

#echo "HDX-Ckan starting in 2 seconds..."
#sleep 2
cd /srv/ckan

[ -z "$NEW_RELIC_APP_NAME"     ] && export NEW_RELIC_APP_NAME="Python Application"
[ -z "$NEW_RELIC_CONFIG_FILE"  ] && export NEW_RELIC_CONFIG_FILE=/srv/newrelic.ini
[ -z "$NEW_RELIC_ENABLED"      ] && export NEW_RELIC_ENABLED=false
[ -z "$NEW_RELIC_LICENSE_KEY"  ] && export NEW_RELIC_LICENSE_KEY="LICENSE"
[ -z "$NEW_RELIC_LOG"          ] && export NEW_RELIC_LOG=false

if [ "$NEW_RELIC_ENABLED" == "true" ]; then
    echo "new relic is enabled."
    newrelic-admin generate-config $NEW_RELIC_LICENSE_KEY $NEW_RELIC_CONFIG_FILE
    exec newrelic-admin run-program gunicorn -w ${HDX_CKAN_WORKERS} --paste /etc/ckan/prod.ini -c /srv/ckan/docker/gunicorn_conf.py
else
    echo "new relic is disabled."
    exec gunicorn -w ${HDX_CKAN_WORKERS} --paste /etc/ckan/prod.ini -c /srv/ckan/docker/gunicorn_conf.py
fi
