# -*- coding: utf-8 -*-

'''
Created on May 11, 2014

@author: alexandru-m-g 
'''
FOCUS_COUNTRIES = [
                u"Afghanistan",
                u"Albania",
                u"Armenia",
                u"Bangladesh",
                u"Belize",
                u"Benin",
                u"Bhutan",
                u"Bolivia (Plurinational State of)",
                u"Burkina Faso",
                u"Burundi",
                u"Cambodia",
                u"Cameroon",
                u"Cape Verde",
                u"Central African Republic",
                u"Chad",
                u"Colombia",
                u"Comoros",
                u"Congo",
                u"Côte d'Ivoire",
                u"Djibouti",
                u"Democratic People's Republic of Korea",
                u"Democratic Republic of the Congo",
                u"Egypt",
                u"El Salvador",
                u"Eritrea",
                u"Ethiopia",
                u"Fiji",
                u"Gambia",
                u"Georgia",
                u"Ghana",
                u"Guatemala",
                u"Guinea",
                u"Guinea-Bissau",
                u"Guyana",
                u"Haiti",
                u"Honduras",
                u"India",
                u"Indonesia",
                u"Iraq",
                u"Kenya",
                u"Kiribati",
                u"Kosovo",
                u"Kyrgyzstan",
                u"Lao People's Democratic Republic",
                u"Lesotho",
                u"Liberia",
                u"Madagascar",
                u"Malawi",
                u"Mali",
                u"Marshall Islands",
                u"Mauritania",
                u"Micronesia, Federated States Of",
                u"Moldova, Republic Of",
                u"Mongolia",
                u"Morocco",
                u"Mozambique",
                u"Myanmar",
                u"Nepal",
                u"Nicaragua",
                u"Niger",
                u"Nigeria",
                u"State of Palestine",
                u"Pakistan",
                u"Papua New Guinea",
                u"Paraguay",
                u"Philippines",
                u"Rwanda",
                u"Samoa",
                u"Sao Tome and Principe",
                u"Senegal",
                u"Sierra Leone",
                u"Solomon Islands",
                u"Somalia",
                u"South Sudan",
                u"Sri Lanka",
                u"Sudan",
                u"Swaziland",
                u"Syrian Arab Republic",
                u"Tajikistan",
                u"United Republic of Tanzania",
                u"East Timor",
                u"Togo",
                u"Tonga",
                u"Uganda",
                u"Ukraine",
                u"Uzbekistan",
                u"Vanuatu",
                u"Viet Nam",
                u"Yemen",
                u"Zambia",
                u"Zimbabwe"
                ]