import os
import re
import argparse
import unicodedata

ICONS_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VIEW_BOXES_FILE = os.path.normpath(os.path.join(ICONS_DIR, '..', '..', '..', 'helpers', 'v2_icon_view_boxes.py'))


def normalize_filename(filename):
    name, ext = os.path.splitext(filename)
    name = unicodedata.normalize('NFKD', name).encode('ascii', 'ignore').decode()
    name = name.lower()
    name = name.replace(" ", "-").replace("_", "-")
    return f"{name}{ext.lower()}"


def process_svg(content, filename, fix_colors=False):
    # Warn if viewBox is missing
    if 'viewBox' not in content:
        print(f"⚠️  WARNING: {filename} has no viewBox")

    # Remove width and height from <svg ...>
    content = re.sub(
        r'<svg[^>]*>',
        lambda match: re.sub(r'\s(width|height)="[^"]+"', '', match.group(0)),
        content,
        count=1,
        flags=re.IGNORECASE
    )

    # Add aria-hidden and focusable before viewBox
    def add_accessibility_attrs(match):
        tag = match.group(0)

        if 'aria-hidden' in tag or 'focusable' in tag:
            return tag  # already present

        if 'viewBox' in tag:
            return tag.replace(
                'viewBox',
                'aria-hidden="true" focusable="false" viewBox'
            )
        else:
            return tag.replace(
                '<svg',
                '<svg aria-hidden="true" focusable="false"'
            )

    content = re.sub(r'<svg[^>]*>', add_accessibility_attrs, content, flags=re.IGNORECASE)

    # Remove Figma's clip-path wrapper and its <defs>
    content = re.sub(
        r'<g clip-path="url\(#[^)]+\)">\n?(.*)</g>\s*<defs>\s*<clipPath[^>]*>.*?</clipPath>\s*</defs>\n?',
        r'\1',
        content,
        flags=re.DOTALL
    )

    if fix_colors:
        # Replace fill (except none)
        content = re.sub(
            r'fill="(?!none)([^"]+)"',
            'fill="currentColor"',
            content,
            flags=re.IGNORECASE
        )

        # Replace stroke (except none)
        content = re.sub(
            r'stroke="(?!none)([^"]+)"',
            'stroke="currentColor"',
            content,
            flags=re.IGNORECASE
        )

    # Wrap the content in <symbol id="i"> for <use href="/v2/icons/<name>.svg#i"/>
    view_box = re.search(r'viewBox="([^"]+)"', content)
    if view_box and '<symbol' not in content:
        root = re.search(r'<svg[^>]*>', content).group(0)
        inner = content.split(root, 1)[1].rsplit('</svg>', 1)[0].strip('\n')
        content = f'{root}\n<symbol id="i" viewBox="{view_box.group(1)}">\n{inner}\n</symbol>\n<use href="#i"/>\n</svg>\n'

    return content


def process_file(filepath, fix_colors):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    new_content = process_svg(content, filepath, fix_colors)

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(new_content)

    return new_content


def main():
    parser = argparse.ArgumentParser(description="Clean SVG files")
    parser.add_argument(
        "--colors",
        action="store_true",
        help="Replace fill/stroke with currentColor (skips locations-flags/)"
    )

    args = parser.parse_args()
    view_boxes = {}

    for root, _, filenames in os.walk(ICONS_DIR):
        fix_colors = args.colors and os.path.basename(root) != 'locations-flags'

        for filename in filenames:
            if filename.lower().endswith('.svg'):
                new_filename = normalize_filename(filename)

                # Rename file if needed
                if filename != new_filename:
                    print(f"Renaming: {filename} → {new_filename}")
                    os.rename(os.path.join(root, filename), os.path.join(root, new_filename))

                print(f"Processing: {new_filename}")
                filepath = os.path.join(root, new_filename)
                content = process_file(filepath, fix_colors)

                # Collect the viewBox for v2_icon_view_boxes.py
                view_box = re.search(r'viewBox="([^"]+)"', content)
                if view_box:
                    icon_path = os.path.relpath(filepath, ICONS_DIR).replace(os.sep, '/')
                    view_boxes[f"v2/icons/{icon_path}"] = view_box.group(1)

    # Write helpers/v2_icon_view_boxes.py for h.hdx_v2_icon
    with open(VIEW_BOXES_FILE, 'w', encoding='utf-8') as f:
        f.write('# Generated by fanstatic/v2/icons/_tools/normalize.py, do not edit.\n\n')
        f.write('V2_ICON_VIEW_BOXES = {\n')
        for icon_path in sorted(view_boxes):
            f.write(f"    '{icon_path}': '{view_boxes[icon_path]}',\n")
        f.write('}\n')
    print(f"Wrote helpers/v2_icon_view_boxes.py ({len(view_boxes)} icons)")

    print("Done!")


if __name__ == "__main__":
    main()
