name: HDX/CKAN create PY3 image

on:
  push:
    tags: [ '*-py3' ]

jobs:
  create-py3-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Branch name
        id: tag_info
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.TEMP_HDX_CKAN_PY3_DOCKERHUB_USER }}
          password: ${{ secrets.TEMP_HDX_CKAN_PY3_DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.py3
          push: true
          tags: mgalex2/hdx-ckan-py3:${{ steps.tag_info.outputs.TAG_NAME }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
