name: HDX/CKAN types checker

on:
  push:
    branches: [ '**' ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ dev ]

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Building CKAN docker image
        run: docker-compose build ckan

      - name: Spinning up docker-compose stack
        run: |
          docker-compose up -d
          sleep 10

      - name: Installing HDX/CKAN PY3 dev-requirements
        run: docker-compose exec -T ckan pip install -r /srv/ckan/dev-requirements.txt

      - name: Install Node.js and npm
        run: |
          docker-compose exec -T ckan bash -c "
          curl -sL https://deb.nodesource.com/setup_22.x | bash -
          apt-get install -y nodejs
          npm install -g pyright
          "

      - name: Check types for ckanext-hdx_dataviz
        run: docker-compose exec -T ckan pyright /srv/ckan/ckanext-hdx_dataviz
        continue-on-error: true

      - name: Check types for ckanext-hdx_hxl_preview
        run: docker-compose exec -T ckan pyright /srv/ckan/ckanext-hdx_hxl_preview
        continue-on-error: true

      - name: Check types for ckanext-hdx_office_preview
        run: docker-compose exec -T ckan pyright /srv/ckan/ckanext-hdx_office_preview
        continue-on-error: true

      - name: Check types for ckanext-hdx_org_group
        run: docker-compose exec -T ckan pyright /srv/ckan/ckanext-hdx_org_group
        continue-on-error: true

      - name: Check types for ckanext-hdx_package
        run: docker-compose exec -T ckan pyright /srv/ckan/ckanext-hdx_package
        continue-on-error: true

      - name: Check types for ckanext-hdx_pages
        run: docker-compose exec -T ckan pyright /srv/ckan/ckanext-hdx_pages
        continue-on-error: true

      - name: Check types for ckanext-hdx_search
        run: docker-compose exec -T ckan pyright /srv/ckan/ckanext-hdx_search
        continue-on-error: true

      - name: Check types for ckanext-hdx_service_checker
        run: docker-compose exec -T ckan pyright /srv/ckan/ckanext-hdx_service_checker
        continue-on-error: true

      - name: Check types for ckanext-hdx_theme
        run: docker-compose exec -T ckan pyright /srv/ckan/ckanext-hdx_theme
        continue-on-error: true

      - name: Check types for ckanext-hdx_user_extra
        run: docker-compose exec -T ckan pyright /srv/ckan/ckanext-hdx_user_extra
        continue-on-error: true

      - name: Check types for ckanext-hdx_users
        run: docker-compose exec -T ckan pyright /srv/ckan/ckanext-hdx_users
        continue-on-error: true

      - name: Check types for ckanext-sitemap
        run: docker-compose exec -T ckan pyright /srv/ckan/ckanext-sitemap
        continue-on-error: true

      - name: Check types for ckanext-ytp-request
        run: docker-compose exec -T ckan pyright /srv/ckan/ckanext-ytp-request
        continue-on-error: true
